// Generated by https://quicktype.io

export interface CatalogResponse {
  code: number;
  description: string;
  data: Data;
}

export interface Data {
  total_products: number;
  items: Product[];
  pagination: Pagination;
  refinements: Refinement[];
  selected_store: string;
}

export interface Product {
  asin: string;
  price: number;
  reviews: Reviews;
  url: string;
  score: number;
  sponsored: boolean;
  amazonChoice: boolean;
  bestSeller: boolean;
  amazonPrime: boolean;
  title: string;
  thumbnail: string;
  position: Position;
  details: Details;
}

export interface Details {
  amazon_price: number;
  price: number;
  total_cost: number;
  suministros: number;
  comision: number;
  utility: number;
  total: number;
}

export interface Position {
  page: number;
  position: number;
  global_position: number;
}

export interface Reviews {
  total_reviews: number;
  rating: number;
}

export interface Pagination {
  current: string;
  previous: string;
  next: Next;
  links: Next[];
}

export interface Next {
  href: string;
  title: string;
}

export interface Refinement {
  price: Base;
  color: string;
  base: Base;
}

export interface Base {
  title: string;
  filters: Filter[];
}

export interface Filter {
  checked: boolean;
  value: string;
  param_value: string;
}
