export const dataMock = [
  {
    code: 200,
    description: "success",
    data: {
      total_products: 44,
      items: [
        {
          asin: "B06X42CKHR",
          price: 878.99,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B06X42CKHR",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title: "Pero Bebida instantÃ¡nea, 7 onzas (paquete de 2)   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/81C2s8WfgFL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 24.19,
            price: 437.5971,
            total_cost: 476.98,
            suministros: 140,
            comision: 62.01,
            utility: 200,
            total: 878.99,
          },
        },
        {
          asin: "B09T9XTH8V",
          price: 353.46,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B09T9XTH8V",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title: "Dog   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/91MZDNLc9CL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 5.99,
            price: 108.3591,
            total_cost: 118.11,
            suministros: 140,
            comision: 15.35,
            utility: 80,
            total: 353.46,
          },
        },
        {
          asin: "B0C6D588VS",
          price: 442.59,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0C6D588VS",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Juguetes para perros para masticadores agresivos, juguetes indestructibles para perros grandes, sabor a tocino real, juguete masticable para perros, huesos para perros de raza mediana/grande, los mejores juguetes agresivos para masticar para perros para mantenerlos ocupados   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71CIhAMWjGL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 9.99,
            price: 180.7191,
            total_cost: 196.98,
            suministros: 140,
            comision: 25.61,
            utility: 80,
            total: 442.59,
          },
        },
        {
          asin: "B09C1Z5P6Q",
          price: 311.18,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B09C1Z5P6Q",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Bandana de otoÃ±o para perro, otoÃ±o, AcciÃ³n de Gracias, a cuadros, reversible, triangular, bufanda, accesorios para perros y mascotas   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/61afWEhMu0L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 4.99,
            price: 90.2691,
            total_cost: 98.39,
            suministros: 140,
            comision: 12.79,
            utility: 60,
            total: 311.18,
          },
        },
        {
          asin: "B0C4TJCRGF",
          price: 440.36,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0C4TJCRGF",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "OLANLY Tapete para puerta de perro para patas fangosas, absorbe la humedad y la suciedad, absorbente, antideslizante, lavable, de microfibra de secado rÃ¡pido, tapete de barro para perros, tapete de entrada para interiores para suelo interior (24 x 16 pulgadas, gris)   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/91c27lj9BsL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 9.89,
            price: 178.9101,
            total_cost: 195.01,
            suministros: 140,
            comision: 25.35,
            utility: 80,
            total: 440.36,
          },
        },
        {
          asin: "B08NJJQ1KW",
          price: 549.44,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B08NJJQ1KW",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Juguetes masticables para perros para masticadores agresivos, indestructibles, resistentes, duraderos, chirriantes, interactivos, para perros con dientes de cachorro, juguete para masticar palitos de maÃ­z para razas pequeÃ±as y medianas y grandes   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71KHlJw+8TL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 12.99,
            price: 234.9891,
            total_cost: 256.14,
            suministros: 140,
            comision: 33.3,
            utility: 120,
            total: 549.44,
          },
        },
        {
          asin: "B07R3KQMMX",
          price: 562.58,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B07R3KQMMX",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Nocciola Paquete de 12 juguetes chirriantes para perros pequeÃ±os y medianos, juguetes para mascotas, juguetes chirriantes, juegos de felpa, bolsa de transporte   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71lMGyBfYkL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 13.58,
            price: 245.6622,
            total_cost: 267.77,
            suministros: 140,
            comision: 34.81,
            utility: 120,
            total: 562.58,
          },
        },
        {
          asin: "B089W25KG3",
          price: 442.59,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B089W25KG3",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Kalimdor Botella de agua para perros, dispensador de agua portÃ¡til a prueba de fugas para cachorros con alimentador para mascotas, caminar al aire libre, senderismo, viajes, plÃ¡stico de grado alimenticio (19 onzas, azul)   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71pou1A0rDL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 9.99,
            price: 180.7191,
            total_cost: 196.98,
            suministros: 140,
            comision: 25.61,
            utility: 80,
            total: 442.59,
          },
        },
        {
          asin: "B07K1P8RQ9",
          price: 300.04,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B07K1P8RQ9",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Paquete de 2 bandanas para perro, diseÃ±o a cuadros de Navidad, reversibles, triangulares, bufandas, accesorios para perros, gatos, mascotas y animales   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/61UD1rO9FPL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 4.49,
            price: 81.2241,
            total_cost: 88.53,
            suministros: 140,
            comision: 11.51,
            utility: 60,
            total: 300.04,
          },
        },
        {
          asin: "B0C39ZB421",
          price: 774.27,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0C39ZB421",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "UUBEI Cama ortopÃ©dica de alta elasticidad para perros de hasta 99 libras, alfombrilla impermeable para mascotas con funda de sherpa lavable de lujo, transpirable, cÃ³moda y duradera, almohadilla para jaula de perro con forro antideslizante para mascotas   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/61U+M2CvREL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 19.49,
            price: 352.5741,
            total_cost: 384.31,
            suministros: 140,
            comision: 49.96,
            utility: 200,
            total: 774.27,
          },
        },
        {
          asin: "B0B8L68Z4H",
          price: 850.24,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0B8L68Z4H",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "AULDEY Funda de asiento de automÃ³vil para perro, impermeable, con ventana de malla y bolsillo de almacenamiento, duradera y antideslizante para perro, con tamaÃ±o universal, se adapta a autos, camiones, SUV   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71qRAmK+kgL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 22.9,
            price: 414.261,
            total_cost: 451.54,
            suministros: 140,
            comision: 58.7,
            utility: 200,
            total: 850.24,
          },
        },
        {
          asin: "B0BL39ZKG3",
          price: 919.09,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0BL39ZKG3",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Niubya Tazones elevados para perros con 2 cuencos de comida de acero inoxidable para perros, cuenco elevado para perros que se ajusta a 5 alturas (3.15, 8.66, 9.84, 11.02, 12.2 pulgadas) para perros pequeÃ±os, medianos y grandes, color gris   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71ZDEsR5cdL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 25.99,
            price: 470.1591,
            total_cost: 512.47,
            suministros: 140,
            comision: 66.62,
            utility: 200,
            total: 919.09,
          },
        },
        {
          asin: "B09G6BJSKW",
          price: 763.13,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B09G6BJSKW",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Funda protectora para asiento trasero de perro, para autos, SUV y camiones con ventana de malla, material antideslizante e impermeable   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/91ZpmbsxY9L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 18.99,
            price: 343.5291,
            total_cost: 374.45,
            suministros: 140,
            comision: 48.68,
            utility: 200,
            total: 763.13,
          },
        },
        {
          asin: "B07N1JYYCW",
          price: 616.28,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B07N1JYYCW",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "AWOOF Alfombrilla de alimentaciÃ³n para olfatear mascotas, rompecabezas para perros, juego interactivo para el aburrimiento, fomenta las habilidades naturales de forraje para gatos, perros, uso portÃ¡til, dispensador de golosinas para perros para aliviar el estrÃ©s en interiores y exteriores   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71Wmu0n5rtL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 15.99,
            price: 289.2591,
            total_cost: 315.29,
            suministros: 140,
            comision: 40.99,
            utility: 120,
            total: 616.28,
          },
        },
        {
          asin: "B094HWN152",
          price: 442.37,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B094HWN152",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Paquete de 2 cepillos de baÃ±o para perros, champÃº de silicona suave para mascotas, dispensador de masaje, cepillo de ducha para lavado de perros y gatos de pelo corto y largo, ISWAYSTORE   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/711qwIyiCVS._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 9.98,
            price: 180.5382,
            total_cost: 196.79,
            suministros: 140,
            comision: 25.58,
            utility: 80,
            total: 442.37,
          },
        },
        {
          asin: "B07GVCFQV6",
          price: 612.72,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B07GVCFQV6",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "PHOEPET - ArnÃ©s reflectante y ajustable para perro con asa de entrenamiento, bolsillo para identificaciÃ³n de nombre, 2 ganchos de metal para correa, 3 hebillas de presiÃ³n [fÃ¡cil de poner y quitar]   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/61sRVUfvoEL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 15.83,
            price: 286.3647,
            total_cost: 312.14,
            suministros: 140,
            comision: 40.58,
            utility: 120,
            total: 612.72,
          },
        },
        {
          asin: "B097RJ3SKT",
          price: 442.59,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B097RJ3SKT",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Kytely Paquete de 2 disfraces de Halloween para perro, bandanas de doble cara de calabaza de Halloween, trajes para perros, gatos, mascotas, bandanas triangulares reversibles para mascotas, bufanda, baberos, accesorios   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71VEik+uN8L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 9.99,
            price: 180.7191,
            total_cost: 196.98,
            suministros: 140,
            comision: 25.61,
            utility: 80,
            total: 442.59,
          },
        },
        {
          asin: "B01MSN3ZLW",
          price: 442.59,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B01MSN3ZLW",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Cera para patas de perro, 100Â % orgÃ¡nica y natural, cura y repara patas heridas   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71wh-v20wEL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 9.99,
            price: 180.7191,
            total_cost: 196.98,
            suministros: 140,
            comision: 25.61,
            utility: 80,
            total: 442.59,
          },
        },
        {
          asin: "B0C23KDMKB",
          price: 1261.91,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0C23KDMKB",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Botones para comunicaciÃ³n para perros, juego de 8 botones para hablar de perros, botones de entrenamiento de voz grabables en 30 segundos, botÃ³n de habla para perros con tapete de botÃ³n antideslizante impermeable y 24 calcomanÃ­as de escena   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71IqSgL8rNL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 35.99,
            price: 651.0591,
            total_cost: 709.65,
            suministros: 140,
            comision: 92.26,
            utility: 320,
            total: 1261.91,
          },
        },
        {
          asin: "B07RWF8X9P",
          price: 284.45,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B07RWF8X9P",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Arm &amp; Hammer Spray sÃºper desodorizante para perros para mascotas | El mejor spray eliminador de olores para todos los perros y cachorros | Aroma fresco de flor de kiwi que huele genial, 8 onzas   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/710Myx0nd4L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 3.79,
            price: 68.5611,
            total_cost: 74.73,
            suministros: 140,
            comision: 9.72,
            utility: 60,
            total: 284.45,
          },
        },
        {
          asin: "B08SWC2MTT",
          price: 442.59,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B08SWC2MTT",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "NTR Correa de entrenamiento de 15 pies para perros, cuerda de nailon con gancho giratorio bloqueable y mango acolchado cÃ³modo, correa para perros pequeÃ±os, medianos y grandes, para entrenamiento, jugar, acampar o patio trasero   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/91Mgkin5HeL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 9.99,
            price: 180.7191,
            total_cost: 196.98,
            suministros: 140,
            comision: 25.61,
            utility: 80,
            total: 442.59,
          },
        },
        {
          asin: "B07SK3R2C3",
          price: 296.04,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B07SK3R2C3",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Chuckit! Ultra Fetch Stick - Juguete para perros al aire libre, para todos los tamaÃ±os de raza   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/41nmK3uuASL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 4.31,
            price: 77.9679,
            total_cost: 84.99,
            suministros: 140,
            comision: 11.05,
            utility: 60,
            total: 296.04,
          },
        },
        {
          asin: "B0C9QH2QB3",
          price: 785.4,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0C9QH2QB3",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title: "Strays (2023)   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/91ykCI0C26L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 19.99,
            price: 361.6191,
            total_cost: 394.16,
            suministros: 140,
            comision: 51.24,
            utility: 200,
            total: 785.4,
          },
        },
        {
          asin: "B09L6P64B8",
          price: 286.67,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B09L6P64B8",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title: "Clifford the Big Red Dog   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/81yTC1LVg1L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 3.89,
            price: 70.3701,
            total_cost: 76.7,
            suministros: 140,
            comision: 9.97,
            utility: 60,
            total: 286.67,
          },
        },
        {
          asin: "B0C4T4LCWM",
          price: 785.4,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0C4T4LCWM",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "POCBLUE Cama lavable de lujo para perros grandes, tapete para jaula de perro de 36 pulgadas, cÃ³moda y esponjosa, antideslizante, para perros de hasta 70 libras, 36 x 23 pulgadas, gris   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71-KSPemFEL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 19.99,
            price: 361.6191,
            total_cost: 394.16,
            suministros: 140,
            comision: 51.24,
            utility: 200,
            total: 785.4,
          },
        },
        {
          asin: "B0CGCMZJPP",
          price: 322.32,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0CGCMZJPP",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Alfombrilla de lamer para perros y gatos con ventosa, almohadilla de lamer premium para aliviar la ansiedad del perro, alfombrilla de alimentaciÃ³n lenta para reducir el aburrimiento, baÃ±arse, aseo y entrenamiento   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71BXbbYcwVL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 5.49,
            price: 99.3141,
            total_cost: 108.25,
            suministros: 140,
            comision: 14.07,
            utility: 60,
            total: 322.32,
          },
        },
        {
          asin: "B0123LGO2Q",
          price: 308.29,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0123LGO2Q",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Huesos comestibles para masticar, para perros de tamaÃ±o grande de hasta 50 lb, sabores silvestres, marca Nylabone, Bisonte, Total 1   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/81BocxBMScS._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 4.86,
            price: 87.9174,
            total_cost: 95.83,
            suministros: 140,
            comision: 12.46,
            utility: 60,
            total: 308.29,
          },
        },
        {
          asin: "B0C4LHT48Z",
          price: 420.31,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0C4LHT48Z",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "MateeyLife Juego de 3 alfombrillas para lamer perros y gatos, tapete para lamer para aliviar la ansiedad del perro, reductor de aburrimiento, almohadilla para lamer mantequilla de manÃ­ para gatos, juguete de enriquecimiento para perros, alfombrilla de golosinas para mascotas para baÃ±o y aseo   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71pNXEn-9-L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 8.99,
            price: 162.6291,
            total_cost: 177.27,
            suministros: 140,
            comision: 23.04,
            utility: 80,
            total: 420.31,
          },
        },
        {
          asin: "B09BBM5CX8",
          price: 353.46,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B09BBM5CX8",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Best Pet Supplies Juguete arrugado para perros para razas pequeÃ±as, medianas y grandes, lindo pato sin relleno con chirriador suave, divertido para cachorros de interior y cachorros mayores, felpa sin ensuciar, masticar y jugar, amarillo   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/61iLNIUwPnL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 5.99,
            price: 108.3591,
            total_cost: 118.11,
            suministros: 140,
            comision: 15.35,
            utility: 80,
            total: 353.46,
          },
        },
        {
          asin: "B0BZZC5PMF",
          price: 398.03,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0BZZC5PMF",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Cepillo de aseo para mascotas y peine de metal, rastrillo para gatos, rastrillo para perros, suministros de aseo, cepillo para quitar pelos, cepillo para quitar pelos, herramienta para mascotas de pelo largo enmaraÃ±ado, azul   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71lhkl+G6EL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 7.99,
            price: 144.5391,
            total_cost: 157.55,
            suministros: 140,
            comision: 20.48,
            utility: 80,
            total: 398.03,
          },
        },
        {
          asin: "B06XG297KD",
          price: 288.91,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B06XG297KD",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title: "A Dog&#x27;s Purpose   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/A1InOEifb+L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 3.99,
            price: 72.1791,
            total_cost: 78.68,
            suministros: 140,
            comision: 10.23,
            utility: 60,
            total: 288.91,
          },
        },
        {
          asin: "B09XXPCB4T",
          price: 593.99,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B09XXPCB4T",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Juguetes de rompecabezas para perros, dispensadores de golosinas chirriantes para entrenamiento de coeficiente intelectual y estimulaciÃ³n cerebral, juguetes interactivos estimulantes mentales como regalos para cachorros, gatos, perros pequeÃ±os, medianos y grandes   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71THE2QseXL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 14.99,
            price: 271.1691,
            total_cost: 295.57,
            suministros: 140,
            comision: 38.42,
            utility: 120,
            total: 593.99,
          },
        },
        {
          asin: "B00L3O3UPE",
          price: 320.32,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B00L3O3UPE",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Outward Hound Fun Feeder Slo Bowl Cuenco para perro de alimentaciÃ³n lenta, mediano/pequeÃ±o, color pÃºrpura   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/61GYYwvN5fL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 5.4,
            price: 97.686,
            total_cost: 106.48,
            suministros: 140,
            comision: 13.84,
            utility: 60,
            total: 320.32,
          },
        },
        {
          asin: "B08N6KWS7T",
          price: 508.88,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B08N6KWS7T",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Kit de 4 huellas y manos sin tinta, almohadilla de tinta para manos y huellas del bebÃ©, kit de impresiÃ³n de huellas de perro, kit de impresiÃ³n de nariz de perro, kit de huellas de bebÃ©, kit de impresiÃ³n de pies de bebÃ© de tacto limpio, kit de huellas de manos (negro azabache)   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71Gmti6zj4L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 11.17,
            price: 202.0653,
            total_cost: 220.25,
            suministros: 140,
            comision: 28.63,
            utility: 120,
            total: 508.88,
          },
        },
        {
          asin: "B00W1QV7XK",
          price: 1082.77,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B00W1QV7XK",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Natural Dog Company Aceite de salmÃ³n puro de Alaska para perros (16 onzas) Suplemento de piel y pelaje para perros, aceite para alimentos con Ã¡cidos grasos esenciales, bomba de aceite de pescado para perros, aceite de salmÃ³n para cachorros, aceite de pescado Omega 3 para perros   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/61xIXE1aaVL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 27.95,
            price: 505.6155,
            total_cost: 551.12,
            suministros: 140,
            comision: 71.65,
            utility: 320,
            total: 1082.77,
          },
        },
        {
          asin: "B0B5PM59Z9",
          price: 288.91,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0B5PM59Z9",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title: "DC League of Super-Pets   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/81Htc2CC5LL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 3.99,
            price: 72.1791,
            total_cost: 78.68,
            suministros: 140,
            comision: 10.23,
            utility: 60,
            total: 288.91,
          },
        },
        {
          asin: "B0002DJZX8",
          price: 350.12,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0002DJZX8",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Nylabone Healthy Edibles - Premios para perro para masticar, 3Â unidades, sabor a tocino (Bacon), S/Regular   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/816gC7FGwaL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 5.84,
            price: 105.6456,
            total_cost: 115.15,
            suministros: 140,
            comision: 14.97,
            utility: 80,
            total: 350.12,
          },
        },
        {
          asin: "B07NYZRCNJ",
          price: 244.34,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B07NYZRCNJ",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title: "The History of the World in Fifty Dogs   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71O4kSA7L8L._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 1.99,
            price: 35.9991,
            total_cost: 39.24,
            suministros: 140,
            comision: 5.1,
            utility: 60,
            total: 244.34,
          },
        },
        {
          asin: "B0BTTPFR8G",
          price: 375.75,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0BTTPFR8G",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Milk-Bone Pride Flavor Snacks - Golosinas para perros, 25 onzas, 25 onzas (paquete de 1)   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/8179lxc8-dL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 6.99,
            price: 126.4491,
            total_cost: 137.83,
            suministros: 140,
            comision: 17.92,
            utility: 80,
            total: 375.75,
          },
        },
        {
          asin: "B0CCHRT5PW",
          price: 442.59,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0CCHRT5PW",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Joytale Collar de perro iluminado, collar de perro con luces LED cortables a prueba de lluvia, collar de silicona suave brillante para perros de seguridad nocturna, 9 modos intermitentes, collar ligero recargable por USB para perros grandes, medianos y pequeÃ±os   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/716KrXqWuOL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 9.99,
            price: 180.7191,
            total_cost: 196.98,
            suministros: 140,
            comision: 25.61,
            utility: 80,
            total: 442.59,
          },
        },
        {
          asin: "B0711Y9Y8W",
          price: 366.83,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0711Y9Y8W",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Nina Ottosson by Outward Hound - Dog Smart - Rompecabezas interactivo para los premios de los perros, color naranja   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/710IzTTY2EL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 6.59,
            price: 119.2131,
            total_cost: 129.94,
            suministros: 140,
            comision: 16.89,
            utility: 80,
            total: 366.83,
          },
        },
        {
          asin: "B09VD8NXTZ",
          price: 718.56,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B09VD8NXTZ",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "Sycoodeal Tapete de cama para perro, tapete de cama para mascotas, tapete de felpa suave, lavable, cÃ³moda cama de piel sintÃ©tica para perros, adecuado para perros medianos y grandes (gris)   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/71VuJQzzLlL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 16.99,
            price: 307.3491,
            total_cost: 335.01,
            suministros: 140,
            comision: 43.55,
            utility: 200,
            total: 718.56,
          },
        },
        {
          asin: "B0C5ZTS8C3",
          price: 1582.45,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B0C5ZTS8C3",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title:
            "INVENHO Cama ortopÃ©dica para perros grandes/medianos, cama grande para perros con forro impermeable, almohadillas extraÃ­bles y funda lavable, cama de espuma para mascotas con parte inferior antideslizante, para perros de hasta 60 libras   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/61Yl1RCN5OL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 44.99,
            price: 813.8691,
            total_cost: 887.12,
            suministros: 140,
            comision: 115.33,
            utility: 440,
            total: 1582.45,
          },
        },
        {
          asin: "B07RG82DYB",
          price: 288.91,
          reviews: {
            total_reviews: 12162,
            rating: 4.6,
          },
          url: "https://amazon.com/dp/B07RG82DYB",
          score: 55945.2,
          sponsored: false,
          amazonChoice: false,
          bestSeller: true,
          amazonPrime: false,
          title: "A Dog&#x27;s Journey   ",
          thumbnail:
            "https://m.media-amazon.com/images/I/91YC46nvEGL._AC_UL320_.jpg",
          position: {
            page: 1,
            position: 36,
            global_position: 34,
          },
          details: {
            amazon_price: 3.99,
            price: 72.1791,
            total_cost: 78.68,
            suministros: 140,
            comision: 10.23,
            utility: 60,
            total: 288.91,
          },
        },
      ],
      pagination: {
        current: "1",
        previous: "",
        next: {
          href: "/s?k=perro&amp&page=2&amp&language=es_US&amp&qid=1697562395&amp&ref=sr_pg_1",
          title: "Siguiente",
        },
        links: [
          {
            href: "",
            title: "1",
          },
          {
            href: "/s?k=perro&amp&page=2&amp&language=es_US&amp&qid=1697562395&amp&ref=sr_pg_2",
            title: "2",
          },
          {
            href: "/s?k=perro&amp&page=3&amp&language=es_US&amp&qid=1697562395&amp&ref=sr_pg_3",
            title: "3",
          },
        ],
      },
      refinements: [
        {
          price: {
            title: "Precio",
            filters: [
              {
                checked: false,
                value: "Oferta del día",
                param_value:
                  "s?&k=perro&amp;rh=p_n_deal_type:23566064011&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=23566063011&amp;ref=sr_nr_p_n_deal_type_1&amp;ds=v1:00UYtZRhSRVp4S01KHdI2xk7FzfNPJZywsAFnUc7gl4",
              },
              {
                checked: false,
                value: "Todos los descuentos",
                param_value:
                  "s?&k=perro&amp;rh=p_n_deal_type:23566065011&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=23566063011&amp;ref=sr_nr_p_n_deal_type_2&amp;ds=v1:o/tLkye6lqkNlXh6YiBCDxjNzjPVk+QGwyhDfQyHjtU",
              },
            ],
          },
          color: "",
          base: {
            title: "Actores",
            filters: [
              {
                checked: false,
                value: "Channing Tatum",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_actors_browse-bin:Channing+Tatum&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2498745011&amp;ref=sr_nr_p_lbr_actors_browse-bin_1&amp;ds=v1:rU7ywWdwu7AD3MyWezsVIHpWLimHsBTQE8VwemhhTqw",
              },
              {
                checked: false,
                value: "Ethan Suplee",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_actors_browse-bin:Ethan+Suplee&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2498745011&amp;ref=sr_nr_p_lbr_actors_browse-bin_2&amp;ds=v1:/al9edn5rv5uxeQuHsttUa6YuqR1q0hjIl4DgqE7l2g",
              },
              {
                checked: false,
                value: "Kevin Nash",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_actors_browse-bin:Kevin+Nash&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2498745011&amp;ref=sr_nr_p_lbr_actors_browse-bin_3&amp;ds=v1:GgPCuQ8Blzz9SfJUi55vMEiY+CoCVU3/1qiMRVyDOpg",
              },
              {
                checked: false,
                value: "Jane Adams",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_actors_browse-bin:Jane+Adams&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2498745011&amp;ref=sr_nr_p_lbr_actors_browse-bin_4&amp;ds=v1:GXB0pILFgRLL3q1p5AERm/Z2LpkItRj9IyM2IbBQDiw",
              },
              {
                checked: false,
                value: "Dennis Quaid",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_actors_browse-bin:Dennis+Quaid&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2498745011&amp;ref=sr_nr_p_lbr_actors_browse-bin_5&amp;ds=v1:avWjx+vNPX7pn8xf0z10mARXd+ZzcDB7VJUuqjkWs2Q",
              },
              {
                checked: false,
                value: "Jared Stern",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_directors_browse-bin:Jared+Stern&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2319120011&amp;ref=sr_nr_p_lbr_directors_browse-bin_1&amp;ds=v1:jYWpjSbeWvEtaMLsNTR2PPOHZyPx32lQP6FDrqnXAYM",
              },
              {
                checked: false,
                value: "Lasse Hallstrom",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_directors_browse-bin:Lasse+Hallstrom&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2319120011&amp;ref=sr_nr_p_lbr_directors_browse-bin_2&amp;ds=v1:JFBQ9PzRUYHJEcJvwBl5knhvpTJ8bWgOURbDLQj0jCg",
              },
              {
                checked: false,
                value: "Gail Mancuso",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_directors_browse-bin:Gail+Mancuso&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2319120011&amp;ref=sr_nr_p_lbr_directors_browse-bin_3&amp;ds=v1:AXTNh6BT5mkWm4OCn54lHKyt7CpIwu2SEHUPeSewyjk",
              },
              {
                checked: false,
                value: "Walt Becker",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_directors_browse-bin:Walt+Becker&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2319120011&amp;ref=sr_nr_p_lbr_directors_browse-bin_4&amp;ds=v1:CLFvTmamxchWKH7HPeDJIYzaoxfcKi6SDb0VEQwJcqg",
              },
              {
                checked: false,
                value: "Geoff Anderson",
                param_value:
                  "s?&k=perro&amp;rh=n:2625373011,p_lbr_directors_browse-bin:Geoff+Anderson&amp;dc&amp;language=es_US&amp;qid=1697562395&amp;rnid=2319120011&amp;ref=sr_nr_p_lbr_directors_browse-bin_5&amp;ds=v1:Gt/Z6hqMmETnZnidmGrU/wrgUFk06p4md6s91jwadQw",
              },
            ],
          },
        },
      ],
      selected_store: "amazon",
    },
  },
];
